-- 코드를 입력하세요
SELECT DATE_FORMAT(a.SALES_DATE,'%Y-%m-%d') AS SALES_DATE, a.PRODUCT_ID,a.USER_ID, a.SALES_AMOUNT 
FROM ONLINE_SALE AS a
WHERE MONTH(SALES_DATE)=3
UNION
SELECT DATE_FORMAT(b.SALES_DATE,'%Y-%m-%d') AS SALES_DATE, b.PRODUCT_ID,NULL,b.SALES_AMOUNT 
FROM OFFLINE_SALE AS b
WHERE MONTH(SALES_DATE)=3
ORDER BY SALES_DATE, PRODUCT_ID, USER_ID